# Generated by Django 6.0.4 on 2026-06-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_review_name_review_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer_name',
            new_name='name',
        ),
    ]
