# Generated by Django 6.0.4 on 2026-06-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_customer_name_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=4.2),
            preserve_default=False,
        ),
    ]
